### ISSUE TITLE
Not working on windows?

### ISSUE THREAD

**Issue by ray007** [flozz/stonejs-tools#2]
When calling `stonejs` either in a CMD shell or a MSys shell, it only ever says `The system cannot find the path specified.`.

Current Windows 7, 64bit, node 0.12.2.

**Comment by flozz** [comment]
Hello,

It should works on Windows too but I haven't tested on that OS... I Will try to check that soon, thank you for your report.

**Comment by flozz** [comment]
Hello,

I found what caused the issue on Windows.

It is now fixed and I updated the NPM package. Just run the `npm install -g stonejs-tools` again to update it and it will work ;)

thank you again for your report!
