### ISSUE TITLE
missing error location

### ISSUE THREAD

**Issue by ray007** [flozz/stonejs-tools#25]
After may months (years?) I had need to run an extraction on my sources again, and I got some errors:
```
WARN: SyntaxError: Unexpected token .
WARN: File skipped due to syntax errors
```
which at the end resulted in
```
108 string(s) extracted, 4 file(s) skipped.
```
Since my app works fine there shouldn't be any syntax errors, and without an error location I cannot go look what it's complaining about.
All that with version `1.2.0` of stonejs-tools.

**Comment by flozz** [comment]
Hello,

you are right, it would be way better to display the position of the syntax error.

This is now fixed in **v1.3.0**, already available on NPM.

Now the output message will looks like that:

```
$ stonejs extract test/fixtures/syntax-error.js out.pot
  * Extracting strings from 'test/fixtures/syntax-error.js'
WARN: Line 1, column 5: SyntaxError: Unexpected token =
WARN: File skipped due to syntax errors
```

**Comment by ray007** [comment]
Thanks.
If you want to know, the parser has a problem with the `object?.property` access.

**Comment by flozz** [comment]
I was pretty sure it would be something like that...

The parser is the same that the one used by ESLint, so it should be able to handle this syntax. I will check if I can update it. :)

**Comment by flozz** [comment]
@ray007 I updated the JS parser and configs to allow using latest ES syntaxes. It should now work out of the box for you :)

(v1.4.0)

**Comment by ray007** [comment]
Thanks, will test soonish.
