### ISSUE TITLE
import / export support

### ISSUE THREAD

**Issue by mebrunet** [flozz/stonejs-tools#5]
I'm running 
```
stonejs extract --functions="__,gettext" "src/**/*.jsx" locales/catalog.pot
```
on a bunch of React/JSX files and getting the warning:
```
WARN: SyntaxError: 'import' and 'export' may appear only with 'sourceType: module'
WARN: File skipped due to syntax errors
```
for each file. So nothing is being extracted. I've tried piping through webpack first as well, but `extract` doesn't seem to recognize the post-processed `gettext` functions. (Not saying this route is impossible... e.g. using `sed`, but would be annoying).

Can I just specify `sourceType:module` somewhere and run on the raw jsx?

**Comment by flozz** [comment]
Hello,

The actual problem is that the parser used by the tools handles only Javascript (ES2015) and not JSX. 

As the tools must be rewrote, I will try to handle JSX when I will work on it.

**Comment by flozz** [comment]
(a temporary solution can be to use babel to transpil jsx to js and use stone-tools on them)

**Comment by mebrunet** [comment]
Ya it doesn't seem to run directly on the transpiled output either... I had to use sed first. Here's a snippet from my package.json scripts in case others find themselves in a similar situation:
```
"extract-text": "mkdir -p temp && webpack --output-path temp --progress && sed -i.tmp \"s/(0, _i18n\\.gettext)/gettext/g\" temp/main.js && stonejs extract temp/main.js locales/catalog.pot && rm -rf temp && stonejs update update locales/*.po locales/catalog.pot",
```
Note my webpack.config set the entry point, and does not minimize without the -p option. You'll need to adjust the substitute command depending on what you name the gettext function.

**Comment by flozz** [comment]
I close this issue as it should now works out of the box
