### ISSUE TITLE
Update Github Actions to use latest NodeJS LTS and non-LTS releases

### ISSUE THREAD

**Issue by Krenodeno** [flozz/stonejs-tools#55]
## Currently

Github Actions runs on a NodeJS versions matrix of v14, 16, 18 and 19

## Target

The version matrix should includes v20 as the latest LTS, and v22 as the latest stable release, or use `latest` alias
We could also remove v19 from tested versions, as it is not the latest anymore, nor a LTS version.

**Comment by flozz** [comment]
Updated :)

→ https://github.com/flozz/stonejs-tools/commit/43f8452b9e9f973adb9520a0418a44e546422a26
